# Generated by Django 3.2.9 on 2022-01-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('price_difference', '-created')},
        ),
    ]
