# Generated by Django 3.2.9 on 2022-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_alter_link_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='prev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_price', models.FloatField(default=0)),
            ],
        ),
    ]
