# Generated by Django 3.2.9 on 2022-01-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0003_prev'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prev',
        ),
    ]
